# Generated by Django 4.2.1 on 2023-06-22 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tienda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_comprac', models.AutoField(primary_key=True, serialize=False)),
                ('fechac', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de compra')),
                ('rutc', models.CharField(default=None, max_length=16)),
                ('totalc', models.IntegerField(default=None, verbose_name='Total de la compra')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rolr', models.AutoField(primary_key=True, serialize=False)),
                ('nombrer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccions', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombrev', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=800)),
                ('precio', models.FloatField(verbose_name='Precio de videojuegos')),
                ('imagenv', models.ImageField(blank=True, default=tienda.models.get_default_image, null=True, upload_to='ImagenVideojuegos', verbose_name='Imagen de videojuegos')),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', unique=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuariou', models.IntegerField(primary_key=True, serialize=False)),
                ('emailu', models.CharField(max_length=30)),
                ('nombre_usuariou', models.CharField(max_length=20)),
                ('contrasenau', models.CharField(max_length=50)),
                ('nombreu', models.CharField(blank=True, max_length=30)),
                ('imagenu', models.ImageField(null=True, upload_to='ImagenUser', verbose_name='Imagen De Usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id_itemcarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.carrito')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.videojuegos')),
            ],
        ),
        migrations.CreateModel(
            name='Detallesc',
            fields=[
                ('id_detallesc', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.FloatField(default=None, verbose_name='Subtotal de la compra')),
                ('cantidad', models.IntegerField(default=None, verbose_name='Cantidad de productos')),
                ('compra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.compra')),
                ('videojuego', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.videojuegos')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.usuario'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.usuario'),
        ),
    ]
