# Generated by Django 4.2.1 on 2023-06-07 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_comprac', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_comprac', models.DateTimeField(auto_now_add=True)),
                ('totalc', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rolr', models.AutoField(primary_key=True, serialize=False)),
                ('nombrer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccions', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombrev', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=800)),
                ('precio', models.FloatField(verbose_name='Precio de videojuegos')),
                ('imagenv', models.ImageField(blank=True, upload_to='ImagenVideojuegos', verbose_name='Imagen de videojuegos')),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', unique=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuariou', models.AutoField(primary_key=True, serialize=False)),
                ('emailu', models.CharField(max_length=30)),
                ('nombre_usuariou', models.CharField(max_length=20)),
                ('contrasenau', models.CharField(max_length=15)),
                ('nombreu', models.CharField(blank=True, max_length=30)),
                ('imagenu', models.ImageField(blank=True, upload_to='ImagenUser', verbose_name='Imagen De Usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Detallesc',
            fields=[
                ('id_detallesd', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadd', models.IntegerField(default=None, verbose_name='cantidad de productos')),
                ('subtotald', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('comprad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.compra')),
                ('videojuegod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.videojuegos')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario'),
        ),
    ]
