# Generated by Django 4.2.1 on 2023-06-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emailu',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuariou',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='descripcion',
            field=models.CharField(max_length=800),
        ),
    ]
