# Generated by Django 4.2.1 on 2023-06-07 23:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='detallesc',
            old_name='id_detallesd',
            new_name='id_detallesc',
        ),
        migrations.RenameField(
            model_name='detallesc',
            old_name='videojuegod',
            new_name='videojuego',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_comprac',
        ),
        migrations.RemoveField(
            model_name='detallesc',
            name='cantidadd',
        ),
        migrations.RemoveField(
            model_name='detallesc',
            name='comprad',
        ),
        migrations.RemoveField(
            model_name='detallesc',
            name='subtotald',
        ),
        migrations.AddField(
            model_name='compra',
            name='fechac',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='rutc',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='detallesc',
            name='cantidad',
            field=models.IntegerField(default=None, verbose_name='Cantidad de productos'),
        ),
        migrations.AddField(
            model_name='detallesc',
            name='compra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.compra'),
        ),
        migrations.AddField(
            model_name='detallesc',
            name='subtotal',
            field=models.FloatField(default=None, verbose_name='Subtotal de la compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='totalc',
            field=models.IntegerField(default=None, verbose_name='Total de la compra'),
        ),
    ]
