# Generated by Django 4.2.1 on 2023-06-17 17:42

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='imagenv',
            field=models.ImageField(blank=True, default=tienda.models.get_default_image, null=True, upload_to='ImagenVideojuegos', verbose_name='Imagen de videojuegos'),
        ),
    ]
