# Generated by Django 4.2.1 on 2023-07-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_historialcompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialCompra',
        ),
    ]
