# Generated by Django 4.2.1 on 2023-06-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_usuario_user_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenau',
            field=models.CharField(max_length=30),
        ),
    ]
