# Generated by Django 4.2.1 on 2023-07-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_historialcompra_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesc',
            name='id_detallesc',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
