# Generated by Django 4.2.1 on 2023-07-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_detallesc_id_detallesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompra',
            name='detalles',
        ),
        migrations.AddField(
            model_name='historialcompra',
            name='detalles',
            field=models.ManyToManyField(to='tienda.detallesc'),
        ),
    ]
