# Generated by Django 4.2.1 on 2023-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_usuario_contrasenau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuariou',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
