# Generated by Django 4.2.1 on 2023-06-18 07:26

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_usuario_id_usuariou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagenu',
            field=models.ImageField(blank=True, default=tienda.models.get_default_image2, upload_to='ImagenUser', verbose_name='Imagen De Usuario'),
        ),
    ]
