# Generated by Django 4.2.1 on 2023-06-18 07:28

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_usuario_imagenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagenu',
            field=models.ImageField(default=tienda.models.get_default_image2, upload_to='ImagenUser', verbose_name='Imagen De Usuario'),
        ),
    ]
